"""empty message

Revision ID: 0ac13616c58d
Revises: df8097af755a
Create Date: 2019-07-08 12:09:00.526071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ac13616c58d'
down_revision = 'df8097af755a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instance_detail', sa.Column('created_by', sa.String(length=255), nullable=False))
    op.add_column('instance_detail', sa.Column('updated_by', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instance_detail', 'updated_by')
    op.drop_column('instance_detail', 'created_by')
    # ### end Alembic commands ###
