"""empty message

Revision ID: 0b7ac720196a
Revises: ecc2faddf6ed
Create Date: 2019-07-09 12:18:58.429109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b7ac720196a'
down_revision = 'ecc2faddf6ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_detail', sa.Column('platform', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image_detail', 'platform')
    # ### end Alembic commands ###
