"""empty message

Revision ID: 2bba797f35cc
Revises: 16b10ee39e4a
Create Date: 2019-07-04 16:26:35.065166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bba797f35cc'
down_revision = '16b10ee39e4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instance_details',
    sa.Column('details_id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.String(length=255), nullable=True),
    sa.Column('image_id', sa.String(length=255), nullable=False),
    sa.Column('instance_type', sa.String(length=255), nullable=False),
    sa.Column('region', sa.Enum('us-east-1', 'us-east-2', 'us-west-1', 'us-west-2', 'ap-south-1', 'ap-northeast-2', 'ap-southeast-1', 'ap-southeast-2', 'ap-northeast-1', 'eu-central-1', 'eu-west-1', 'sa-east-1'), nullable=True),
    sa.Column('state', sa.Enum('pending', 'running', 'shutting-down', 'terminated', 'stopping', 'stopped', 'rebooting'), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['instance.instance_id'], ),
    sa.PrimaryKeyConstraint('details_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instance_details')
    # ### end Alembic commands ###
