"""empty message

Revision ID: 2c8e39568dfc
Revises: 0ac13616c58d
Create Date: 2019-07-08 15:39:15.108828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c8e39568dfc'
down_revision = '0ac13616c58d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('public', sa.Boolean(), nullable=False),
    sa.Column('state', sa.Enum('pending', 'available', 'invalid', 'deregistered', 'transient', 'failed', 'error'), nullable=True),
    sa.Column('Name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_detail')
    # ### end Alembic commands ###
