"""empty message

Revision ID: 4aa52b9dad41
Revises: 0b5935e48e80
Create Date: 2019-07-01 17:29:25.206333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aa52b9dad41'
down_revision = '0b5935e48e80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instance',
    sa.Column('iid', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('instance_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('iid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instance')
    # ### end Alembic commands ###
