"""empty message

Revision ID: 4e63d1f34651
Revises: d2a589ededcc
Create Date: 2019-07-08 16:49:33.637845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e63d1f34651'
down_revision = 'd2a589ededcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('public', sa.Boolean(), nullable=False),
    sa.Column('state', sa.Enum('pending', 'available', 'invalid', 'deregistered', 'transient', 'failed', 'error'), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_detail')
    # ### end Alembic commands ###
