"""empty message

Revision ID: 5b050c8ce536
Revises: 0918d16c9629
Create Date: 2019-07-04 16:54:58.460286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b050c8ce536'
down_revision = '0918d16c9629'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instance_detail',
    sa.Column('details_id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.String(length=255), nullable=True),
    sa.Column('image_id', sa.String(length=255), nullable=False),
    sa.Column('instance_type', sa.String(length=255), nullable=False),
    sa.Column('region', sa.Enum('us-east-1', 'us-east-2', 'us-west-1', 'us-west-2', 'ap-south-1', 'ap-northeast-2', 'ap-southeast-1', 'ap-southeast-2', 'ap-northeast-1', 'eu-central-1', 'eu-west-1', 'sa-east-1'), nullable=True),
    sa.Column('state', sa.Enum('pending', 'running', 'shutting-down', 'terminated', 'stopping', 'stopped', 'rebooting'), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['instance.instance_id'], ),
    sa.PrimaryKeyConstraint('details_id')
    )
    op.create_unique_constraint(None, 'instance', ['instance_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'instance', type_='unique')
    op.drop_table('instance_detail')
    # ### end Alembic commands ###
