"""empty message

Revision ID: b60503be4ef5
Revises: 15885310988f
Create Date: 2019-07-08 10:53:38.139107

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b60503be4ef5'
down_revision = '15885310988f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instance_detail')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instance_detail',
    sa.Column('instance_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('image_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('instance_type', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('state', mysql.ENUM('pending', 'running', 'shutting-down', 'terminated', 'stopping', 'stopped', 'rebooting'), nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('key_name', mysql.VARCHAR(length=255), server_default=sa.text("'WinServer2012'"), nullable=False),
    sa.Column('zone', mysql.ENUM('us-east-1', 'us-east-2', 'us-west-1', 'us-west-2', 'ap-south-1', 'ap-northeast-2', 'ap-southeast-1', 'ap-southeast-2', 'ap-northeast-1', 'eu-central-1', 'eu-west-1', 'sa-east-1'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
