"""empty message

Revision ID: c3bfce586f50
Revises: 2c8e39568dfc
Create Date: 2019-07-08 16:44:35.822168

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c3bfce586f50'
down_revision = '2c8e39568dfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_detail', sa.Column('name', sa.String(length=255), nullable=True))
    op.drop_column('image_detail', 'Name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_detail', sa.Column('Name', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('image_detail', 'name')
    # ### end Alembic commands ###
