"""empty message

Revision ID: d2a589ededcc
Revises: 54aeacdbdb0d
Create Date: 2019-07-08 16:46:50.185490

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd2a589ededcc'
down_revision = '54aeacdbdb0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_detail')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_detail',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('image_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('location', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('public', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('state', mysql.ENUM('pending', 'available', 'invalid', 'deregistered', 'transient', 'failed', 'error'), nullable=True),
    sa.Column('Name', mysql.VARCHAR(length=255), nullable=True),
    sa.CheckConstraint('(`public` in (0,1))', name='image_detail_chk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
