"""empty message

Revision ID: df8097af755a
Revises: b60503be4ef5
Create Date: 2019-07-08 10:54:50.035326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df8097af755a'
down_revision = 'b60503be4ef5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instance_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.String(length=255), nullable=False),
    sa.Column('image_id', sa.String(length=255), nullable=False),
    sa.Column('instance_type', sa.String(length=255), nullable=False),
    sa.Column('zone', sa.String(length=255), nullable=False),
    sa.Column('state', sa.Enum('pending', 'running', 'shutting-down', 'terminated', 'stopping', 'stopped', 'rebooting'), nullable=True),
    sa.Column('key_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instance_detail')
    # ### end Alembic commands ###
