"""empty message

Revision ID: ecc2faddf6ed
Revises: 4e63d1f34651
Create Date: 2019-07-08 17:45:45.017297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecc2faddf6ed'
down_revision = '4e63d1f34651'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_detail', sa.Column('architecture', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image_detail', 'architecture')
    # ### end Alembic commands ###
